### ISSUE TITLE
TRaI increases drops drastically and reduces kills needed for flags.

### ISSUE THREAD

**Issue by joelou1** [HiKoNe/TRaI1.3#1]
**Issue:**
Whenever TRaI is installed, droptables are highly increased and banners now drop every 2 kills rather than the regular 50 kills. This can be combersome and game breaking.

**Expectance:**
TRaI should only allow people to see recipes, as advertised.

**Steps:**

- Download TRaI
- Open a world
- Slay some creatures/slimes
- Obtain super rare items like the slime staff (Which is a 1/10000 chance for this instance) at an absurd rate (1/10?) and swim in banners.

**Note (If Any):**
I have Calamity (+ Music), Magic Storage and Hero's Mod installed as well, with no issues prior to installing TRaI. I'd like to say that I've been looking for a mod similar to NEI from Minecraft, but for Terraria, and this mod definitely fits the bill, but I'd rather not have unfair chances by adding this mod. Please fix!

![Bannerbug](https://user-images.githubusercontent.com/1740156/144729288-751c2b89-8247-4c74-8c3e-41ed26d917c5.png)
![image](https://user-images.githubusercontent.com/1740156/144729298-1ab524c3-16cd-4a71-a5bd-c4027eea2dd7.png)

**Comment by HiKoNe** [comment]
Oops, need fix
